apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsegate-config
  namespace: pulsegate
data:
  POSTGRES_HOST: "postgres-svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "pulsegate"
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-svc:9092"
